[2023-12-12 19:10:49,898] ERROR log_exception() L825  Exception on /reserva [POST] - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py L825 
Traceback (most recent call last):
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/app.py", line 70, in predict
    outcome = Model.preditor(modelo, form)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/model/modelo.py", line 41, in preditor
    scaler = StandardScaler().fit(X_input) # aplica√ß√£o da padroniza√ß√£o no conjunto de treino
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 824, in fit
    return self.partial_fit(X, y, sample_weight)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 861, in partial_fit
    X = self._validate_data(
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/utils/validation.py", line 902, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[  3.   8.   0.   9.   1.   0.   0.   0.   0.   0. 100.   0.   0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
[2023-12-12 19:10:50,028] INFO _log() L96   127.0.0.1 - - [12/Dec/2023 19:10:50] "[35m[1mPOST /reserva HTTP/1.1[0m" 500 - - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L96  
[2023-12-12 19:10:59,422] INFO _log() L96    * Detected change in '/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/model/modelo.py', reloading - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L96  
[2023-12-12 19:11:03,785] ERROR log_exception() L825  Exception on /reserva [POST] - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py L825 
Traceback (most recent call last):
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/app.py", line 70, in predict
    outcome = Model.preditor(modelo, form)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/model/modelo.py", line 41, in preditor
    scaler = StandardScaler().fit(X_input) # aplica√ß√£o da padroniza√ß√£o no conjunto de treino
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 824, in fit
    return self.partial_fit(X, y, sample_weight)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 861, in partial_fit
    X = self._validate_data(
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/utils/validation.py", line 902, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[  3.   8.   0.   9.   1.   0.   0.   0.   0.   0. 100.   0.   0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
[2023-12-12 19:11:03,794] INFO _log() L96   127.0.0.1 - - [12/Dec/2023 19:11:03] "[35m[1mPOST /reserva HTTP/1.1[0m" 500 - - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L96  
[2023-12-12 19:11:14,144] INFO _log() L96    * Detected change in '/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/model/modelo.py', reloading - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L96  
[2023-12-12 19:11:18,481] ERROR log_exception() L825  Exception on /reserva [POST] - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py L825 
Traceback (most recent call last):
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/app.py", line 70, in predict
    outcome = Model.preditor(modelo, form)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/model/modelo.py", line 42, in preditor
    rescaledX = scaler.transform(X_input)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/utils/_set_output.py", line 140, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/preprocessing/_data.py", line 992, in transform
    X = self._validate_data(
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/base.py", line 565, in _validate_data
    X = check_array(X, input_name="X", **check_params)
  File "/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/sklearn/utils/validation.py", line 902, in check_array
    raise ValueError(
ValueError: Expected 2D array, got 1D array instead:
array=[  3.   8.   0.   9.   1.   0.   0.   0.   0.   0. 100.   0.   0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.
[2023-12-12 19:11:18,495] INFO _log() L96   127.0.0.1 - - [12/Dec/2023 19:11:18] "[35m[1mPOST /reserva HTTP/1.1[0m" 500 - - call_trace=/Users/conradocosta/Desktop/Pos/Sprint 2/Sprint2_MVP/api/env_app/lib/python3.9/site-packages/werkzeug/_internal.py L96  
